micronaut:
  application:
    name: cleanURI-apigateway
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /oas3/**
netty:
  default:
    allocator:
      max-order: 3

cleanuri:
  results:
      cache-cleanup: "300s"
